version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:

  django: &django
    container_name: django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    #image: jordotech_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8011:8000"
    command: /start
  frontend:
    entrypoint: ["sh", "-c", "sleep 2073600"]
    container_name: map
    #command: gatsby develop -p 8000 -H 0.0.0.0 --verbose
    build: # how to build the frontend
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/map:/app:delegated
    ports:
      - "8012:8000"
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: jordotech_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0
