# Generated by Django 2.2.4 on 2019-11-18 01:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.IntegerField(help_text='Identifier for this vessel', unique=True, verbose_name='MMSI')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, help_text='Auto filled by system on save based on address.', null=True, verbose_name='latitude')),
                ('lon', models.FloatField(blank=True, help_text='Auto filled by system on save based on address.', null=True, verbose_name='longitude')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.Vessel')),
            ],
        ),
    ]
