# Generated by Django 2.2.4 on 2019-11-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.IntegerField(help_text='Identifier for this vessel', unique=True, verbose_name='MMSI')),
                ('total_positions', models.IntegerField(default=0, verbose_name='Positions Recorded')),
                ('dist_covered', models.FloatField(default=0, verbose_name='Distance Covered')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('sort', models.IntegerField(default=0, verbose_name='Sort')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.Vessel')),
            ],
        ),
    ]
