# Generated by Django 2.2.4 on 2019-11-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='dt',
        ),
        migrations.AddField(
            model_name='position',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Sort'),
        ),
    ]
